print glog_version
glog_version = '0.3.4'
print glog_version

cc_library(
    name = 'variables',
    srcs = [
    ],
    deps = [
    '#pthread',
    '//thirdparty/glog/' + glog_version + ':glog',
   ]
)

