dist: bionic
language: python
python:
  - "2.7"
  - "3.6"
  - "3.9"

before_install: true

install:
  - pip install coverage
  - pip install coveralls

addons:
  apt:
    sources:
      - kubuntu-backports
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build

script:
  - src/test/runall.sh

after_success:
  - coveralls
