language: python
python:
  - "2.7"

before_install: true

addons:
  apt:
    sources:
    - kubuntu-backports
    - ubuntu-toolchain-r-test
    packages:
    - ninja-build
    
script:
  - cpp --version
  - gcc -v
  - g++ -v
  - src/test/runalltests.sh
