cc_library(
    name = 'template_cpu',
    srcs = ['template_cpu.cpp'],
    hdrs = [],
)

"""
cu_binary(
    name = 'template',
    srcs = ['template.cu'],
    deps = [':template_cpu'],
)

cu_test(
    name = 'cu_test',
    srcs = ['cu_test.cu'],
    deps = [':template_cpu'],
)
"""
