py_binary(
    name = 'exe',
    srcs = 'exe.py',
    deps = [
        '//py/lib:lib',
        '//py/proto:echo_proto',
    ]
)

py_binary(
    name = 'exe2',
    srcs = ['exe2.py'],
    deps = [
        '//py/lib:lib',
        '//py/proto:echo_proto',
    ],
    main = 'exe2.py',
)

